- hosts: hosts
  become: true
  roles:
    - hosts
  tasks:
    - wait_for:
        host: "{{hostvars[item].ip}}"
        port: 50000
        timeout: 3600
      with_inventory_hostnames:
        - managers
        - workers
