- name: Download arch
  get_url: 
    url: "{{item}}"    
    dest: /vm/tftp/arch/
  with_items:
    - http://mirror.yandex.ru/archlinux/iso/latest/arch/boot/x86_64/vmlinuz
    - http://mirror.yandex.ru/archlinux/iso/latest/arch/boot/intel_ucode.img
    - http://mirror.yandex.ru/archlinux/iso/latest/arch/boot/x86_64/archiso.img
    - http://mirror.yandex.ru/archlinux/iso/latest/arch/x86_64/airootfs.sfs

- name: Copy pxe config
  copy:
    src: files/arch_pxe.cfg
    dest: /vm/tftp/arch/

- name: Copy syslinux
  command: cp -aR /usr/lib/syslinux/bios /vm/tftp/arch/syslinux

- name: Unpack squashfs
  command: unsquashfs -d /vm/tftp/arch/squashfs-root /vm/tftp/arch/airootfs.sfs

- name: Modify squashfs install
  template:
    src: templates/{{item}}.j2
    dest: /vm/tftp/arch/squashfs-root/etc/systemd/system/{{item}}.service
  with_items:
    - install
    - post-install

- name: Enable install service
  file:
    src: /etc/systemd/system/install.service
    dest: /vm/tftp/arch/squashfs-root/etc/systemd/system/multi-user.target.wants/install.service
    state: link
    force: yes

- name: Enable sshd service
  file:
    src: /usr/lib/systemd/system/sshd.service
    dest: /vm/tftp/arch/squashfs-root/etc/systemd/system/multi-user.target.wants/sshd.service
    state: link
    force: yes

- name: Remove hostname
  file:
    path: /vm/tftp/arch/squashfs-root/etc/hostname
    state: absent
    force: yes

- name: Pack squashfs
  command: mksquashfs /vm/tftp/arch/squashfs-root /vm/tftp/arch/x86_64/airootfs.sfs

