- include: virt-node.yml
  with_inventory_hostnames:
    - managers
    - workers

- name: Waiting to install...
  wait_for:
    host: "{{hostvars[item].ip}}"
    port: 50001
    timeout: 3600
  with_inventory_hostnames:
    - managers
    - workers

- virt:
    name: "{{item}}"
    command: destroy
  with_inventory_hostnames:
    - managers
    - workers

- virt:
    name: "{{item}}"
    command: start
  with_inventory_hostnames:
    - managers
    - workers

- name: Waiting to reboot...
  wait_for:
    host: "{{hostvars[item].ip}}"
    port: 50000
    timeout: 3600
  with_inventory_hostnames:
    - managers
    - workers
